# Generated by Django 4.2.11 on 2024-04-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['id'], name='id_index'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['uuid'], name='uuid_index'),
        ),
    ]
